// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cognito_identity_pool_id': 'us-east-1:b664e90d-e934-440d-ad16-97399db45ac3',
    'aws_cognito_region': 'us-east-1',
    'aws_project_id': 'b3a8c824-850b-4b98-9df5-66bd666c3cef',
    'aws_project_name': 'InterviewJS',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'interviewjs-mobilehub-1138514045',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'interviewjs-userfiles-mobilehub-1138514045',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_cVCr9fuwI',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '7d9mpe4i4qfjbd5ps88t0u29eu',
    'aws_user_settings': 'enable',
}

export default awsmobile;
